package provider

import (
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/sdk"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/advisor"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/analysisservices"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/apimanagement"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/appconfiguration"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/applicationinsights"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/appservice"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/attestation"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/authorization"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/automation"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/azurestackhci"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/batch"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/billing"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/blueprints"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/bot"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/cdn"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/cognitive"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/communication"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/compute"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/consumption"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/containers"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/cosmos"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/costmanagement"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/customproviders"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/databasemigration"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/databoxedge"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/databricks"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/datafactory"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/datalake"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/dataprotection"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/datashare"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/desktopvirtualization"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/devspace"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/devtestlabs"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/digitaltwins"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/dns"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/domainservices"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/eventgrid"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/eventhub"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/firewall"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/frontdoor"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/hdinsight"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/healthcare"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/hpccache"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/hsm"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/iotcentral"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/iothub"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/iottimeseriesinsights"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/keyvault"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/kusto"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/lighthouse"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/loadbalancer"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/loganalytics"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/logic"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/logz"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/machinelearning"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/maintenance"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/managedapplications"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/managementgroup"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/maps"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/mariadb"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/media"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/mixedreality"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/monitor"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/msi"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/mssql"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/mysql"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/netapp"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/network"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/notificationhub"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/policy"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/portal"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/postgres"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/powerbi"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/privatedns"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/purview"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/recoveryservices"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/redis"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/redisenterprise"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/relay"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/resource"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/search"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/securitycenter"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/sentinel"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/servicebus"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/servicefabric"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/servicefabricmesh"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/signalr"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/springcloud"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/sql"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/storage"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/streamanalytics"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/subscription"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/synapse"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/trafficmanager"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/videoanalyzer"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/vmware"
	"github.com/kevinklinger/terraform-provider-azurerm/v2/internal/services/web"
)

//go:generate go run ../tools/generator-services/main.go -path=../../

func SupportedTypedServices() []sdk.TypedServiceRegistration {
	return []sdk.TypedServiceRegistration{
		apimanagement.Registration{},
		appconfiguration.Registration{},
		appservice.Registration{},
		batch.Registration{},
		eventhub.Registration{},
		loadbalancer.Registration{},
		mssql.Registration{},
		policy.Registration{},
		resource.Registration{},
		streamanalytics.Registration{},
		web.Registration{},
	}
}

func SupportedUntypedServices() []sdk.UntypedServiceRegistration {
	return []sdk.UntypedServiceRegistration{
		advisor.Registration{},
		analysisservices.Registration{},
		apimanagement.Registration{},
		appconfiguration.Registration{},
		springcloud.Registration{},
		applicationinsights.Registration{},
		attestation.Registration{},
		authorization.Registration{},
		automation.Registration{},
		azurestackhci.Registration{},
		batch.Registration{},
		billing.Registration{},
		blueprints.Registration{},
		bot.Registration{},
		cdn.Registration{},
		cognitive.Registration{},
		communication.Registration{},
		compute.Registration{},
		containers.Registration{},
		consumption.Registration{},
		cosmos.Registration{},
		costmanagement.Registration{},
		customproviders.Registration{},
		databricks.Registration{},
		datafactory.Registration{},
		datalake.Registration{},
		databasemigration.Registration{},
		databoxedge.Registration{},
		dataprotection.Registration{},
		datashare.Registration{},
		desktopvirtualization.Registration{},
		devspace.Registration{},
		devtestlabs.Registration{},
		digitaltwins.Registration{},
		dns.Registration{},
		domainservices.Registration{},
		eventgrid.Registration{},
		eventhub.Registration{},
		firewall.Registration{},
		frontdoor.Registration{},
		hpccache.Registration{},
		hsm.Registration{},
		hdinsight.Registration{},
		healthcare.Registration{},
		iothub.Registration{},
		iotcentral.Registration{},
		keyvault.Registration{},
		kusto.Registration{},
		loadbalancer.Registration{},
		loganalytics.Registration{},
		logic.Registration{},
		logz.Registration{},
		machinelearning.Registration{},
		maintenance.Registration{},
		managedapplications.Registration{},
		lighthouse.Registration{},
		managementgroup.Registration{},
		maps.Registration{},
		mariadb.Registration{},
		media.Registration{},
		mixedreality.Registration{},
		monitor.Registration{},
		msi.Registration{},
		mssql.Registration{},
		mysql.Registration{},
		netapp.Registration{},
		network.Registration{},
		notificationhub.Registration{},
		policy.Registration{},
		portal.Registration{},
		postgres.Registration{},
		powerbi.Registration{},
		privatedns.Registration{},
		purview.Registration{},
		recoveryservices.Registration{},
		redis.Registration{},
		redisenterprise.Registration{},
		relay.Registration{},
		resource.Registration{},
		search.Registration{},
		securitycenter.Registration{},
		sentinel.Registration{},
		servicebus.Registration{},
		servicefabric.Registration{},
		servicefabricmesh.Registration{},
		signalr.Registration{},
		sql.Registration{},
		storage.Registration{},
		streamanalytics.Registration{},
		subscription.Registration{},
		synapse.Registration{},
		iottimeseriesinsights.Registration{},
		trafficmanager.Registration{},
		videoanalyzer.Registration{},
		vmware.Registration{},
		web.Registration{},
	}
}
